{
 "title": "dash-forum-api",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UPTIME",
   "type": "stat",
   "description": "API Uptime",
   "gridPos": { "h": 3, "w": 5, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "START TIME",
   "type": "stat",
   "description": "Start  time from application",
   "gridPos": { "h": 3, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USERS LOGGED",
   "type": "stat",
   "description": "Users logged at last minute",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auth_user_success_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JDBC POOL",
   "type": "stat",
   "description": "Connection's pool JDBC.",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WARN & ERROR LOG",
   "type": "timeseries",
   "description": "Warning and error in last 5 minutes",
   "gridPos": { "h": 6, "w": 18, "x": 1, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"warn\"}[5m]))",
     "legendFormat": "warn"
    },
    {
     "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"error\"}[5m]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "DB TIMEOUT",
   "type": "stat",
   "description": "Database's connection timeout",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Errors",
   "type": "stat",
   "description": "Authentication errors in last minute",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auth_user_error_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CONNECTION STATE",
   "type": "timeseries",
   "description": "Connection state with database",
   "gridPos": { "h": 7, "w": 18, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
     "legendFormat": "active"
    },
    {
     "expr": "hikaricp_connections_idle{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
     "legendFormat": "pending"
    }
   ]
  }
 ]
}